// app/layout.tsx
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import dynamic from 'next/dynamic';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const DynamicReactQueryProvider = dynamic(() => import('@/context/ReactQueryProvider'), { ssr: false });
const DynamicAuthProvider = dynamic(() => import('@/context/AuthProvider'), { ssr: false });

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DynamicReactQueryProvider>
          <DynamicAuthProvider>
            {children}
            <Toaster />
          </DynamicAuthProvider>
        </DynamicReactQueryProvider>
      </body>
    </html>
  );
}
